version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: local-ta-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=5m
    volumes:
      - ./models:/root/.ollama


